#!/usr/bin/env bash

verify() {
    echo "🧪 Running Maven verify..."
    mvn -q verify
}

IS_TAG_PUSH=false

while read local_ref local_sha remote_ref remote_sha
do
    #
    # Block pushes to main
    #
    if [[ "$local_ref" == refs/heads/main ]]; then
        echo "🚫 Push to main is strictly blocked by this hook."
        exit 1
    fi

    #
    # Release validation
    #
    if [[ "$local_ref" == refs/tags/v* ]]; then
        IS_TAG_PUSH=true
        TAG_VERSION="${local_ref#refs/tags/v}"
        ./scripts/validate-release.sh "$TAG_VERSION"
    fi
done

if verify; then
    echo "✅ Maven verification passed."
    exit 0
fi

echo
echo "❌ Maven verification failed."

if [ "$IS_TAG_PUSH" = true ]; then
    echo "🚫 Tag push aborted."
    exit 1
fi

echo "⚠️ Push allowed despite failing verification."
echo "⚠️ CI will likely fail."

exit 0