package eu.nicosworld.rithmo.engine.capture.justification;

import eu.nicosworld.rithmo.engine.math.progression.ProgressionResult;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public sealed interface ProgressionEvidence
    permits ArithmeticJustification, GeometricJustification, HarmonicJustification {

  /**
   * Extracts all valid progression evidences from a ProgressionResult. It scans through all
   * triplets generated by the engine to find arithmetic, geometric, or harmonic patterns.
   *
   * @param result the engine's progression analysis result
   * @return an immutable set of discovered evidences
   * @throws IllegalArgumentException if no progression was detected at all
   */
  static Set<ProgressionEvidence> from(ProgressionResult result) {
    if (!result.isAny()) {
      throw new IllegalArgumentException("No progression detected");
    }

    // Process all triplets (handles 1 triplet for 3 pieces, or multiple for 4 pieces)
    return result.triplets().stream()
        .flatMap(
            triplet -> {
              List<ProgressionEvidence> evidences = new ArrayList<>();

              if (triplet.isArithmetic()) {
                evidences.add(new ArithmeticJustification(triplet.mid() - triplet.min()));
              }
              if (triplet.isGeometric()) {
                evidences.add(new GeometricJustification((double) triplet.mid() / triplet.min()));
              }
              if (triplet.isHarmonic()) {
                evidences.add(new HarmonicJustification());
              }

              return evidences.stream();
            })
        .collect(Collectors.toUnmodifiableSet()); // Guarantees immutability and uniqueness
  }
}
